# XXX: Update this file correctly (esp. URL)
baseURL = 'http://example.org/'
languageCode = 'de'
title = 'Aurealm Pen & Paper'
theme = 'aurealm'

[params]
  # "relatedtext" is the text that appears above the tag list at the bottom of pages.
  relatedtext = "Related"
  favicon = "/favicon.ico"

  #list items
  datesinlist = true
  authorsinlist = true

  #footer items
  nextprev = true
  taglist = true
  showrss = true
